language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"

install:
  - "pip install -r tests/requirements.txt"
  - "python setup.py install"

script:
  - "flake8 tests pubsubclub"
  - "python tests/"
  - "python tests/test_consul_discovery.py"
